---
- name: "Create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Uncompress backend tar files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install node dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "Run node using PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  
  register: execute_node

- name: printout msgs
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Config PM2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu -hp /home/ubuntu